version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    REPOSITORY_URI: 512138916710.dkr.ecr.us-east-1.amazonaws.com/organic

phases:
  install:
    commands:
      - echo Installing...

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"organic-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
